<?php


namespace Drupal\spotify_artists\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

class SpotifySettings extends ConfigFormBase {

  /**
   * @inheritDoc
   */
  protected function getEditableConfigNames() {
    return [
      'spotify_artists.settings',
    ];
  }

  /**
   * @inheritDoc
   */
  public function getFormId() {
    return 'spotify_artists_settings';
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    $config = $this->config('spotify_artists.settings');

    $form['api_url'] = [
      '#type' => 'textfield',
      '#name' => 'api_url',
      '#title' => $this->t('API Url'),
      '#default_value' => $config->get('api_url'),
      '#required' => TRUE,
    ];

    $form['account_url'] = [
      '#type' => 'textfield',
      '#name' => 'account_url',
      '#title' => $this->t('Account Url'),
      '#default_value' => $config->get('account_url'),
      '#required' => TRUE,
    ];

    $form['client_id'] = [
      '#type' => 'textfield',
      '#name' => 'client_id',
      '#title' => $this->t('Client ID'),
      '#default_value' => $config->get('client_id'),
      '#required' => TRUE,
    ];

    $form['client_secret'] = [
      '#type' => 'password',
      '#name' => 'client_secret',
      '#title' => $this->t('Client Secret'),
      '#default_value' => $config->get('client_secret'),
      '#required' => FALSE,
    ];

    if (empty($config->get('client_secret'))) {
      $form['client_secret']['#required'] = TRUE;
    }

    $form['redirect_uri'] = [
      '#type' => 'textfield',
      '#name' => 'redirect_uri',
      '#title' => $this->t('Redirect URI'),
      '#default_value' => $config->get('redirect_uri'),
      '#required' => TRUE,
    ];

    $form['artists_ids'] = [
      '#type' => 'textarea',
      '#name' => 'artists_ids',
      '#title' => $this->t('Artists Ids'),
      '#default_value' => $config->get('artists_ids'),
      '#required' => TRUE,
    ];

    return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {
    $values = $form_state->getValues();
    $this->config('spotify_artists.settings')
      ->set('api_url', $values['api_url'])
      ->set('account_url', $values['account_url'])
      ->set('client_id', $values['client_id'])
      ->set('client_secret', $values['client_secret'])
      ->set('redirect_uri', $values['redirect_uri'])
      ->set('artists_ids', $values['artists_ids'])
      ->save();
  }
}
